---
title: "3 stress methods at fedecoop sites"
author: "Mikaela M. Provost"
date: "11/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(grid)
library(gridExtra)
library(cowplot)
library(ggrepel)
library(pracma)
library(viridis)
library(lemon)
library(lubridate)
library(zoo)
library(tidyverse)
library(stats)
library(sf)
library(viridis)


# load functions --> ***** CHECK for MG or MP *****
source("C:/Users/Mikaela/Documents/GitHub/natividad/functions.r")


```

  

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
# -- Read in bottom data -- #

d <- read.csv(file="C:/Users/Mikaela/Documents/GitHub/natividad/data/001_FEDECOOP_MS_DATA.csv",stringsAsFactors = FALSE)
d$Date <- as.Date(d$UTC_DateTime,format="%Y-%m-%d") # create date-only column
bottomall <- d %>% 
  group_by(Site,Date) %>% 
  sample_n(1) %>% 
  select(Site,Temperature,Date)# randomly select temp per day

#names(bottomall)[names(bottomall)=="Temperature"] <- "temp_bottom"
rm(d)
site_vector <- unique(bottomall$Site)


# testing --------
# n_occur <- data.frame(table(bottomall[bottomall$Site==site_vector[9],]$Date))
# n_occur[n_occur$Freq >1,]
  
  

```




```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
# -------------------------------------------
# Method 1: area under short-term variability curve
# -------------------------------------------
wts <- c(0.1,0.2,0.4,0.8)
wts <- wts/sum(wts)
wtsp <- round(wts*100,digits=0)
auc_method1 <- data.frame(
  Site = site_vector,
  area_method1 = rep(NA,length=length(site_vector)))
  
stress_list <- as.list(rep(NA,length=length(site_vector)))
names(stress_list) <- site_vector

for(s in 1:length(site_vector)){
  
  stress_list[[s]] <- calc_stress(d=bottomall[bottomall$Site==site_vector[s],],
                                weights=wtsp)  
  stress <- stress_list[[s]]
  
  yy <- abs(stress[stress$Site==site_vector[s],]$Dstress)
  yy <- yy[!is.na(yy)]
  xx <- seq(from=1,to=length(yy),by=1)
  auc_method1[auc_method1$Site == site_vector[s],]$area_method1 <- trapz(x=xx,y=yy)
  rm(yy,xx,stress)
  
}
bottomall_stress <- do.call("rbind",stress_list)



# -------------------------------------------
# Method 2: area under temperature curve for when temp is >20C
# -------------------------------------------
auc_method2 <- data.frame(
  Site = site_vector,
  area_method2 = rep(NA,length=length(site_vector)))
bottomall_stress$Temperature_20 <- ifelse(bottomall_stress$Temperature < 20,0,bottomall_stress$Temperature)

for(s in 1:length(site_vector)){
  d <- bottomall_stress[bottomall_stress$Site==site_vector[s],]
  xx <- seq(from=1,to=length(d$Temperature),by=1)
  auc_method2[auc_method2$Site == site_vector[s],]$area_method2 <- (trapz(x=xx,y=d$Temperature_20))#/(length(d$Temperature_20>0))
  
}


# -------------------------------------------
# Method 3: degree heating week
# -------------------------------------------
# for each week, sum temperature that is >20 C 
# plot these time series for each site
dhwL <- as.list(rep(NA,length=length(site_vector)))
names(dhwL) <- site_vector

window_length = 8

for(s in 1:length(site_vector)){
  d <- bottomall_stress[bottomall_stress$Site==site_vector[s],]
  
  # how many weeks are there? rounding down
  
  df <- data.frame(site = rep(site_vector[s],length=floor(length(d[,1])/window_length)),
                   weeknum = seq(from=1,to=floor(length(d[,1])/window_length),by=1),
                   startdate = seq(from=d$Date[1],to=d$Date[window_length*floor(length(d[,1])/window_length)-(window_length-1)],by=window_length),
                   enddate = seq(from=d$Date[window_length],to=d$Date[window_length*floor(length(d[,1])/window_length)],by=window_length),
                   dhw = rep(NA,length=floor(length(d[,1])/window_length))  )
  
  for(i in 1:length(df$weeknum)){ #step through dates
    # subset temp data to window
    tsub <- d[d$Date >= df$startdate[i] & d$Date <= df$enddate[i],]
    df$dhw[i] <- sum(tsub$Temperature_20)
  }
  
  dhwL[[s]] <- df
  rm(tsub,df,d)
}
dhw_df <- do.call('rbind',dhwL)

```

### Plot short-term variability stress time series

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, fig.width=11, fig.height=35}

p <- as.list(rep(NA,length=length(site_vector)))
for(s in 1:length(site_vector)){
  d <- bottomall_stress[bottomall_stress$Site == site_vector[s],]
  p[[s]] <- ggplot(data=d) +
    geom_point(aes(x=Date,y=Dstress,color=Temperature_20)) +
    scale_color_viridis(begin = 0,end = 1) +
    geom_line(aes(x=Date,y=Dstress,color=Temperature_20)) +
    ggtitle(paste(site_vector[s])) +
    ylab("Expected T - Experienced T") + xlab("date") +
    ylim(-2,2) +
    theme_bw() +
    geom_abline(slope=0,intercept = 0,color="grey",linetype='dashed')
}
do.call(grid.arrange,c(p,ncol=2))
rm(p)
```



```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, fig.width=9, fig.height=8}

```


### Plot bottom temperature time series, dashed line = 20 C

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, fig.width=11, fig.height=35}

p <- as.list(rep(NA,length=length(site_vector)))
for(s in 1:length(site_vector)){
  d <- bottomall[bottomall$Site == site_vector[s],]
  p[[s]] <- ggplot(data=d) +
    #geom_point(aes(x=Date,y=Temperature)) +
    geom_line(aes(x=Date,y=Temperature)) +
    ggtitle(paste(site_vector[s])) +
    ylab("temp") + xlab("date") +
    ylim(8,27) +
    theme_bw() +
    geom_abline(slope=0,intercept = 20,color="red",linetype='dashed')
}
do.call(grid.arrange,c(p,ncol=2))
```

### Plot degree heating week

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, fig.width=11, fig.height=35}
p <- as.list(rep(NA,length=length(site_vector)))
for(s in 1:length(site_vector)){
  d <- dhw_df[dhw_df$site == site_vector[s],]
  p[[s]] <- ggplot(data=d) +
    geom_point(aes(x=enddate,y=dhw)) +
    geom_line(aes(x=enddate,y=dhw)) +
    ggtitle(paste(site_vector[s])) +
    ylab("DHW (8 day window)") + xlab("date") +
    ylim(0,210) +
    theme_bw() 
}
do.call(grid.arrange,c(p,ncol=2))

```

### Map of method 2: area under temperature curve for temps >20C

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, fig.width=12, fig.height=7}
# get the shapefile
f <- st_read("C:/Users/Mikaela/Documents/GitHub/natividad/shapefiles/FEDECOOP.shp")
s <- st_read("C:/Users/Mikaela/Documents/GitHub/natividad/shapefiles/countries.shp")


locations <- read.csv("C:/Users/Mikaela/Documents/GitHub/natividad/data/Sensor_Locations_map.csv")
names(locations)[1] <- "Site"
locations <- left_join(locations,auc_method1,by='Site')
locations <- left_join(locations,auc_method2,by='Site')

p1<-ggplot() +
  geom_sf(data=s) +
  geom_sf(data=f,col='grey60',fill='grey',alpha=0.3) +
  coord_sf(ylim=c(26,29), xlim=c(-116,-112.5)) +
  geom_point(data=locations,aes(x=Longtitude,y=Latitude,color=area_method1),size=5) +
  scale_color_viridis(direction = -1) +
  geom_text_repel(data=locations[!locations$Site %in% c('Monterey','VanDamme','Sportfish','LaJolla'),],
                  aes(x=Longtitude, y=Latitude,label = Site,color=area_method1),
                  segment.color = "grey30",
                  size = 4,
                  na.rm = TRUE,
                  nudge_x = -0.2,
                  box.padding = 1) +
  theme_bw() + xlab("") +ylab("")

p2<-ggplot() +
  geom_sf(data=s) +
  geom_sf(data=f,col='grey60',fill='grey',alpha=0.3) +
  coord_sf(ylim=c(26,29), xlim=c(-116,-112.5)) +
  geom_point(data=locations,aes(x=Longtitude,y=Latitude,color=area_method2),size=5) +
  scale_color_viridis(direction = 1) +
  geom_text_repel(data=locations[!locations$Site %in% c('Monterey','VanDamme','Sportfish','LaJolla'),],
                  aes(x=Longtitude, y=Latitude,label = Site,color=area_method2),
                  segment.color = "grey30",
                  size = 4,
                  na.rm = TRUE,
                  nudge_x = -0.2,
                  box.padding = 1) +
  theme_bw() + xlab("") +ylab("")

plot_grid(p1,p2)

```

