---
title: "Variance Regression"
author: "Mikaela M. Provost"
date: "10/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(tidyverse)
library(grid)
library(gridExtra)
library(cowplot)
library(ggrepel)
library(pracma)
library(viridis)
library(lemon)
library(lubridate)
library(zoo)


#install.packages('viridis')

# load functions --> ***** CHECK for MG or MP *****
source("C:/Users/Mikaela/Documents/GitHub/natividad/functions.r")

# # Plan
# 1. For each site, check if site-specific temperature offset and 2.5 deg C offset has different impacts on stress time series.
# 2. See if depth correlates with site-specific average offset.
# 3. Check to see if variance in bottom temperature correlates with variance in SST. Does variance correlate for each month? We might expect SST and bottom temperature to be less correlated during upwelling.
# 4. Quantify amount of variance at high frequencies in bottom temperature. Add this variance to smoothed SST time series.

```

  

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
# -- Read in data -- #

# read in data - bottom
d <- read.csv(file="C:/Users/Mikaela/Documents/GitHub/natividad/data/001_FEDECOOP_MS_DATA.csv",stringsAsFactors = FALSE)
d$Date <- as.Date(d$UTC_DateTime,format="%Y-%m-%d") # create date-only column
bottomfede <- d %>% group_by(Site,Date) %>% sample_n(1) %>% select(Site,Temperature,Date)# randomly select temp per day
d1 <- read.csv(file="C:/Users/Mikaela/Documents/GitHub/natividad/data/001_IslaNatividad_MorroPrietoPuntaPrieta_alldata_trimmed.csv",stringsAsFactors = FALSE)
d1$Date <- as.Date(d1$UTC_Date_Time,format="%Y-%m-%d")
bottommppp <- d1 %>% 
  filter(Site %in% c('MorroPrieto','PuntaPrieta'), Instrument_Type == 'MiniDOT') %>% 
  group_by(Site,Date) %>% 
  sample_n(1) %>% 
  select(Site,Temperature,Date)
bottomall <- rbind(bottomfede,bottommppp)
names(bottomall)[names(bottomall)=="Temperature"] <- "temp_bottom"
rm(d1,d,bottomfede,bottommppp)

# read in data - SST
m <- read.csv(file= "C:/Users/Mikaela/Documents/GitHub/natividad/data/morroprieto_temp.csv",stringsAsFactors = FALSE)
p <- read.csv(file= "C:/Users/Mikaela/Documents/GitHub/natividad/data/puntaprieta_temp.csv",stringsAsFactors = FALSE)
m$Site <- rep("Morro_Prieto")
p$Site <- rep("Punta_Prieta")
p$datetime <- as.Date(p$datetime,format="%m/%d/%Y") #more fun with dates
m$datetime <- as.Date(m$datetime,format="%m/%d/%Y") #I hate dates
file_names <- list.files(path = "C:/Users/Mikaela/Documents/GitHub/natividad/data/sstfedecoop",pattern = "csv") 
file_names <- unlist(strsplit(file_names,split="_temp.csv"), use.names=FALSE)
filesL <- as.list(rep(NA,length=length(file_names)))
names(filesL) <- file_names
for(f in 1:length(file_names)){
  filesL[[f]] <- read.csv(paste("C:/Users/Mikaela/Documents/GitHub/natividad/data/sstfedecoop/",
                file_names[f],"_temp.csv",sep=""),stringsAsFactors = FALSE)} #end loop
SSTfede <- bind_rows(filesL,.id="Site")
SSTfede$datetime <- as.Date(SSTfede$datetime,format="%d-%b-%Y") #date problems
SSTall <- bind_rows(p,m,SSTfede)
SSTall <- SSTall %>% select(datetime,temp,Site,flag)
names(SSTall)[names(SSTall)=="datetime"] <- "Date"
names(SSTall)[names(SSTall)=="temp"] <- "temp_sst"
rm(f,m,p,SSTfede,filesL,file_names)

# standardize site location names
sitekey <- read.csv(file="C:/Users/Mikaela/Documents/GitHub/natividad/data/siteskey_fixed.csv",stringsAsFactors = F)
sitekey <- sitekey[complete.cases(sitekey),]
SSTall$bsite <- sitekey[match(SSTall$Site,sitekey$Ssites),"bsites"]
bottomall$Ssite <- sitekey[match(bottomall$Site,sitekey$bsites),"Ssites"] 
bottomall$Site <- NULL
colnames(bottomall)[colnames(bottomall)=="Ssite"] <- "Site"


# add column for just raw data (NA where no raw data)
# Flag is 0 if the points are data, 1 if point is estimated.
SSTall$temp_sst_raw <- rep(NA,length=length(SSTall[,1]))
SSTall$temp_sst_raw <- ifelse(SSTall$flag < 1, SSTall$temp_sst, "NA")
SSTall$temp_sst_raw <- as.numeric(as.character(SSTall$temp_sst_raw))

# create day index key
SSTall <- SSTall %>%
          mutate(year = year(Date),
                 month = month(Date),
                 day = day(Date),
                 julian_day = yday(Date))


# apply 30 day smoother to SST data
smoothingwindow=30
site_vector <- unique(SSTall$Site)
SSTall$temp_smooth <- rep(0,length=length(SSTall[,1]))
SSTall$temp_smooth_raw <- rep(0,length=length(SSTall[,1]))
for(s in 1:length(site_vector) ){
  
  # smooth over raw + interpolated 
  SSTall[SSTall$Site == site_vector[s],]$temp_smooth <- 
    ma(SSTall[SSTall$Site == site_vector[s],]$temp_sst,n=smoothingwindow)
  
  # smooth over raw
  SSTall[SSTall$Site == site_vector[s],]$temp_smooth_raw <- 
    ma(SSTall[SSTall$Site == site_vector[s],]$temp_sst_raw,n=smoothingwindow)
  
 
  
  #d <- SSTall[SSTall$Site == site_vector[s],]
  #years <- unique(d$year)
  
  #for(y in 1:length(years)){
  #  SSTall[SSTall$Site == site_vector[s] & SSTall$year == years[y],]$temp_smooth <- 
  #  as.numeric(ma(d[d$year==years[y],]$temp_sst,n=smoothingwindow))
    
  #}
  
}

# subtract seasonal trend from temps, get deviations
SSTall$temp_dev <- rep(0,length=length(SSTall[,1]))
SSTall$temp_dev_raw <- rep(0,length=length(SSTall[,1]))
for(s in 1:length(site_vector) ){
  # dev in raw + interpolated
  SSTall[SSTall$Site == site_vector[s],]$temp_dev <- 
    SSTall[SSTall$Site == site_vector[s],]$temp_sst - SSTall[SSTall$Site == site_vector[s],]$temp_smooth
  # dev in raw 
  SSTall[SSTall$Site == site_vector[s],]$temp_dev_raw <- 
    SSTall[SSTall$Site == site_vector[s],]$temp_sst_raw - SSTall[SSTall$Site == site_vector[s],]$temp_smooth_raw
}

# store mean annual variance for each site in SSTvar
SSTvar <- data.frame(
  Site = site_vector,
  mean_annual_var = rep(NA,length=length(site_vector)),
  mean_annual_var_raw = rep(NA,length=length(site_vector))
)




for(s in 1:length(site_vector)){ # for each site
  
  # store variance per year in v (these will be averaged)
  years <- unique(SSTall[SSTall$Site==site_vector[s],]$year)
  v     <- rep(NA,length=length(years))
  v_raw <- rep(NA,length=length(years))
  
  for(y in 1:length(years)){ # for each year, calculate variance in deviations
    
    # raw + interpolated
    v[y] <- var(SSTall[SSTall$Site==site_vector[s] & SSTall$year==years[y],]$temp_dev,na.rm=TRUE)
    
    # raw 
    v_raw[y] <- var(SSTall[SSTall$Site==site_vector[s] & SSTall$year==years[y],]$temp_dev_raw,na.rm = TRUE)
  }
  # average the variance values from all years for each site
  SSTvar[SSTvar$Site==site_vector[s],]$mean_annual_var <- mean(v)
  SSTvar[SSTvar$Site==site_vector[s],]$mean_annual_var_raw <- mean(v_raw)
  rm(v,years,v_raw)
}

combo <- bottomall

write.csv(SSTall, file="C:/Users/Mikaela/Documents/GitHub/natividad/data/SSTall2.csv")
write.csv(SSTvar, file="C:/Users/Mikaela/Documents/GitHub/natividad/data/regression2.csv")
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, fig.width=11, fig.height=35}
site_vector <- unique(SSTall$Site)
p <- as.list(rep(NA,length=length(site_vector)))
for(s in 1:length(site_vector)){
  d <- SSTall[SSTall$Site == site_vector[s],]
  p[[s]] <- ggplot(data=d) +
    geom_point(aes(x=Date,y=temp_sst_raw,color="raw")) +
    geom_line(aes(x=Date,y=temp_smooth_raw,color="smooth")) +
    ggtitle(paste(site_vector[s])) +
    xlab("temp") + ylab("date")
}
do.call(grid.arrange,c(p,ncol=2))
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
# ---------------------------------------------------------------
# Calculate high freq variance in bottom (using 10 min data)
# ---------------------------------------------------------------

# read in data - bottom fedecoop
d <- read.csv(file="C:/Users/Mikaela/Documents/GitHub/natividad/data/001_FEDECOOP_MS_DATA.csv",stringsAsFactors = FALSE)
d$Date <- as.Date(d$UTC_DateTime,format="%Y-%m-%d") # create date-only column
colnames(d)[colnames(d) == "UTC_DateTime"] <- "UTC_Date_Time"
bottomfede <- d %>% select(Site,Temperature,Date,UTC_Date_Time)

# read in data - bottom mm & mp
d1 <- read.csv(file="C:/Users/Mikaela/Documents/GitHub/natividad/data/001_IslaNatividad_MorroPrietoPuntaPrieta_alldata_trimmed.csv",stringsAsFactors = FALSE)
d1$Date <- as.Date(d1$Date,format="%Y-%m-%d")
bottommppp <- d1 %>% 
  filter(Site %in% c('MorroPrieto','PuntaPrieta'), Instrument_Type == 'MiniDOT') %>% 
  select(Site,Temperature,Date,UTC_Date_Time)
bottomall <- rbind(bottomfede,bottommppp)
colnames(bottomall)[colnames(bottomall)=="Temperature"] <- "temp_bottom"
rm(d1,d,bottomfede,bottommppp)

# standardize site location names
bottomall$Ssite <- sitekey[match(bottomall$Site,sitekey$bsites),"Ssites"] 
bottomall$Site <- NULL
colnames(bottomall)[colnames(bottomall)=="Ssite"] <- "Site"


# ----------
# -- spectrums -- #
# ----------
sampleinterval = 10/(10*6*24)
site_vector <- unique(bottomall$Site)

pBR <- as.list(rep(NA,length=length(site_vector)))
pBRlog <- as.list(rep(NA,length=length(site_vector)))
regressiondf <- data.frame(
  Site = site_vector,
  highvar_bottom = rep(NA,length=length(site_vector)))

for(s in 1:length(site_vector)){ #for each site
  
  # subset to site
  d <- bottomall[bottomall$Site == site_vector[s],]
  
  # SST spectrum 
  spR <- spec.pgram(d$temp_bottom,spans=NULL,taper=0.1,plot = FALSE,demean = TRUE)
  
  spRdf <- data.frame(
    freq = spR$freq/sampleinterval,
    freq1 = spR$freq,
    spec = spR$spec*(spR$freq/sampleinterval),
    spec1 = spR$spec)
  
  # store plots
  pBRlog[[s]] <- ggplot(data=spRdf,aes(x=log10(freq),y=log10(spec))) + 
    geom_line() + ggtitle(paste(d$Site[1]," - 10 min data",sep="")) +
    xlab("log10(freq (1/day))") + ylab("log10(spec*freq)") +
    theme(legend.position="none") 
  
  pBR[[s]] <- ggplot(data=spRdf[spRdf$freq < 10,],aes(x=freq,y=log10(spec))) + 
    geom_line() + ggtitle(paste(d$Site[1]," - 10 min data",sep="")) +
    xlab("freq (1/day)") + ylab("log10(spec*freq)") +
    theme(legend.position="none") 
  
  regressiondf[regressiondf$Site == site_vector[s],]$highvar_bottom <- 
    trapz(x=spRdf[spRdf$freq > 0.75 & spRdf$freq < 2.25 ,]$freq1,
          y=spRdf[spRdf$freq > 0.75 & spRdf$freq < 2.25 ,]$spec1 * 2)
  
    #sum(spRdf[spRdf$freq > 0.75 & spRdf$freq < 2.25,]$spec1 * min(spRdf$freq)) 
}
rm(spRdf,d,s,spR,site_vector)


```


```{r include=FALSE, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
# ---------------------------------------------------------------
# Calculate variance in smoothed SST
# Create mSST (add columns to combo df)
# ---------------------------------------------------------------
# smoothingwindow=30
# 
# #combosave <- combo
# #combo <- combosave
# 
# site_vector <- unique(combo$Site)
# pDev <- as.list(rep(NA,length(site_vector)))
# names(pDev) <- site_vector
# combo$smoothSST_mean <- rep(NA,length=length(combo[,1]))
# combo$SSTdeviations_mean <- rep(NA,length=length(combo[,1])) # just the high frequency variability in SST
# 
# combo$smoothSST_max <- rep(NA,length=length(combo[,1]))
# combo$SSTdeviations_max <- rep(NA,length=length(combo[,1]))
# 
# combo$smoothSST_rand <- rep(NA,length=length(combo[,1]))
# combo$SSTdeviations_rand <- rep(NA,length=length(combo[,1]))
# 
# combo$smoothSST_median <- rep(NA,length=length(combo[,1]))
# combo$SSTdeviations_median <- rep(NA,length=length(combo[,1]))
# 
# for(s in 1:length(site_vector)){ #for each site
#   
#   dd <- combo[combo$Site==site_vector[s],]
#   
#   dd$smoothSST_mean <- as.numeric(ma(dd$temp_sst_mean,n=smoothingwindow)) # smooth SST with 30 day window
#   dd$SSTdeviations_mean <- as.numeric((dd$temp_sst_mean - dd$smoothSST_mean)) # remove seasonal variation
#   
#   dd$smoothSST_max <- as.numeric(ma(dd$temp_sst_max,n=smoothingwindow)) 
#   dd$SSTdeviations_max <- as.numeric((dd$temp_sst_max - dd$smoothSST_max))
#   
#   dd$smoothSST_rand <- as.numeric(ma(dd$temp_sst_rand,n=smoothingwindow)) 
#   dd$SSTdeviations_rand <- as.numeric((dd$temp_sst_rand - dd$smoothSST_rand))
#   
#   dd$smoothSST_median <- as.numeric(ma(dd$temp_sst_median,n=smoothingwindow)) 
#   dd$SSTdeviations_median <- as.numeric((dd$temp_sst_median - dd$smoothSST_median))
#   
#   
#   pDev[[s]] <- ggplot(data=dd) +
#     geom_point(aes(x=Date,y=SSTdeviations_mean,color="SST high freq (mean jul day)")) +
#     geom_point(aes(x=Date,y=SSTdeviations_max,color="SST high freq (max jul day)")) +
#     geom_point(aes(x=Date,y=SSTdeviations_rand,color="SST high freq (random jul day)")) +
#     geom_point(aes(x=Date,y=SSTdeviations_median,color="SST high freq (median jul day)")) +
#     ggtitle(paste(dd$Site[1])) +
#     #ylim(-4,28) +
#     ylab("Temperature") + xlab("Date")
#   
#   
#   combo[combo$Site==site_vector[s],]$smoothSST_mean <- # add smoothed SST to combo
#     dd[match(combo[combo$Site==site_vector[s],]$julian_day,dd$julian_day),"smoothSST_mean"]
#   combo[combo$Site==site_vector[s],]$SSTdeviations_mean <- # add col of SST deviations 
#     dd[match(combo[combo$Site==site_vector[s],]$julian_day,dd$julian_day),"SSTdeviations_mean"]
#   
#   combo[combo$Site==site_vector[s],]$smoothSST_max <- # add smoothed SST to combo
#     dd[match(combo[combo$Site==site_vector[s],]$julian_day,dd$julian_day),"smoothSST_max"]
#   combo[combo$Site==site_vector[s],]$SSTdeviations_max <- # add col of SST deviations 
#     dd[match(combo[combo$Site==site_vector[s],]$julian_day,dd$julian_day),"SSTdeviations_max"]
#   
#   combo[combo$Site==site_vector[s],]$smoothSST_rand <- # add smoothed SST to combo
#     dd[match(combo[combo$Site==site_vector[s],]$julian_day,dd$julian_day),"smoothSST_rand"]
#   combo[combo$Site==site_vector[s],]$SSTdeviations_rand <- # add col of SST deviations 
#     dd[match(combo[combo$Site==site_vector[s],]$julian_day,dd$julian_day),"SSTdeviations_rand"]
#   
#   combo[combo$Site==site_vector[s],]$smoothSST_median <- # add smoothed SST to combo
#     dd[match(combo[combo$Site==site_vector[s],]$julian_day,dd$julian_day),"smoothSST_median"]
#   combo[combo$Site==site_vector[s],]$SSTdeviations_median <- # add col of SST deviations 
#     dd[match(combo[combo$Site==site_vector[s],]$julian_day,dd$julian_day),"SSTdeviations_median"]
#   
#   regressiondf[regressiondf$Site == site_vector[s],]$highvar_sst_meanjul <- 
#     var(dd$SSTdeviations_mean,na.rm=TRUE) # variance of SST deviations
#   
#   regressiondf[regressiondf$Site == site_vector[s],]$highvar_sst_maxjul <- 
#     var(dd$SSTdeviations_max,na.rm=TRUE) # variance of SST deviations
#   
#   regressiondf[regressiondf$Site == site_vector[s],]$highvar_sst_randjul <- 
#     var(dd$SSTdeviations_rand,na.rm=TRUE) # variance of SST deviations
#   
#   regressiondf[regressiondf$Site == site_vector[s],]$highvar_sst_medianjul <- 
#     var(dd$SSTdeviations_median,na.rm=TRUE) # variance of SST deviations
#   
# }
# ggplot(data=combo[combo$Site=="Morro_Prieto" & combo$julian_day %in% seq(from=1,to=100,by=1),]) +
#   geom_line(aes(x=julian_day,y=temp_sst,color="SST jul day temp")) +
#   geom_line(aes(x=julian_day,y=smoothSST,color="smoothed SST jul day")) 
# 



```



```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE}
# Plot regression

regressiondf <- left_join(regressiondf,SSTvar)
colnames(sitekey)[colnames(sitekey)=="Ssites"] <- "Site"
regressiondf <- left_join(regressiondf,sitekey)
#write.csv(regressiondf, file="C:/Users/Mikaela/Documents/GitHub/natividad/data/regression.csv")

regressiondf_sub <- regressiondf[!regressiondf$brock_plot==0,]
regressiondf_sub3 <- regressiondf[!regressiondf$bsites %in% c("PuntaPrieta","Monterey"),]

m1 <- lm(regressiondf$mean_annual_var_raw ~ regressiondf$highvar_bottom)
m2 <- lm(regressiondf_sub$mean_annual_var_raw ~ regressiondf_sub$highvar_bottom)
m3 <- lm(regressiondf_sub3$mean_annual_var_raw ~ regressiondf_sub3$highvar_bottom)


lm_eqn_mean <- function(df){ # function to paste regression & r2 on plot
  x = df$highvar_bottom
  y = df$mean_annual_var_raw
    m <- lm(y ~ x, df);
    eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2, 
         list(a = format(unname(coef(m)[1]), digits = 2),
              b = format(unname(coef(m)[2]), digits = 2),
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq)); }

```


```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, fig.width=5, fig.height=6}
ggplot(data=regressiondf,aes(x=highvar_bottom, y=mean_annual_var_raw)) +
  geom_point() +
  geom_abline(slope=m2$coefficients[2],intercept = m2$coefficients[1]) +
  theme_classic() +
  #xlim(0,0.6) + ylim(0,0.5) +
  geom_text(x = 0.4, 
            y = 0.7, 
            label = lm_eqn_mean(regressiondf_sub), parse = TRUE) +
  xlab("bottom var [C^2]") +
  ylab("SST var [C^2] (raw data only)") +
  geom_text_repel(data=regressiondf[!regressiondf$Site %in% regressiondf_sub$Site,],
                  aes(x=highvar_bottom, y=mean_annual_var_raw,label = bsites),
                  color="blue",
                  segment.color = "grey",
                  size = 3,
                  na.rm = TRUE,
                  box.padding = 0.5) +
  geom_text_repel(data=regressiondf_sub,
                  aes(x=highvar_bottom, y=mean_annual_var_raw,label = bsites),
                  color="darkgrey",
                  segment.color = "grey",
                  size = 3,
                  na.rm = TRUE,
                  box.padding = 0.5) +
  ggtitle("Blue sites not in Brock's plot (not included in regression)")
```

```{r echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, fig.width=5, fig.height=6}

ggplot(data=regressiondf,aes(x=highvar_bottom, y=mean_annual_var_raw)) +
  geom_point() +
  geom_abline(slope=m3$coefficients[2],intercept = m3$coefficients[1]) +
  theme_classic() +
  #xlim(0,0.6) + ylim(0,0.5) +
  geom_text(x = 0.4, 
            y = 0.7, 
            label = lm_eqn_mean(regressiondf_sub3), parse = TRUE) +
  xlab("bottom var [C^2]") +
  ylab("SST var [C^2] (raw data only)") +
  geom_text_repel(data=regressiondf[!regressiondf$Site %in% regressiondf_sub3$Site,],
                  aes(x=highvar_bottom, y=mean_annual_var_raw,label = bsites),
                  color="blue",
                  segment.color = "grey",
                  size = 3,
                  na.rm = TRUE,
                  box.padding = 0.5) +
  geom_text_repel(data=regressiondf_sub3,
                  aes(x=highvar_bottom, y=mean_annual_var_raw,label = bsites),
                  color="darkgrey",
                  segment.color = "grey",
                  size = 3,
                  na.rm = TRUE,
                  box.padding = 0.5) +
  ggtitle("Blue sites not in regression")


```





